### ISSUE TITLE
Installing requirements does not work

### ISSUE THREAD

**Issue by Novahem** [rgm89git/ntscQTplus#8]
Using Windows 10, I installed Python, FFMPEG, and Git with Scoop. I am also using Windows Terminal as recommended. Other commands prior to the outlier run correctly, but when running `pip install -r requirements.txt`, it fails at a few things seemingly related to the version of python installed (3.12.0) using the command in the README verbatim (`scoop install python`). I feel I have followed every step as closely as possible, though I would certainly prefer there be an obvious solution that I missed that can solve this issue instantly. Below is the relevant error log. If there is any solution to this, that would be great.

PS D:\Blender Stuff\\ntscqt\pluscompilebetter\ntscQTplus> ./venv/Scripts/activate.ps1
(venv) PS D:\Blender Stuff\\ntscqt\pluscompilebetter\ntscQTplus> pip install -r requirements.txt
Collecting ffmpeg-python>=0.2.0 (from -r requirements.txt (line 1))
  Using cached ffmpeg_python-0.2.0-py3-none-any.whl (25 kB)
Collecting future>=0.18.2 (from -r requirements.txt (line 2))
  Using cached future-0.18.3.tar.gz (840 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting imutils>=0.5.4 (from -r requirements.txt (line 3))
  Using cached imutils-0.5.4.tar.gz (17 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy>=1.21.5 (from -r requirements.txt (line 4))
  Obtaining dependency information for numpy>=1.21.5 from https://files.pythonhosted.org/packages/32/95/908d0caa051beae4f7c77652dbbeb781e7b717f3040c5c5fcaed4d3ed08f/numpy-1.26.1-cp312-cp312-win_amd64.whl.metadata
  Using cached numpy-1.26.1-cp312-cp312-win_amd64.whl.metadata (61 kB)
Collecting darkdetect>=0.5.1 (from -r requirements.txt (line 5))
  Using cached darkdetect-0.8.0-py3-none-any.whl (9.0 kB)
ERROR: Ignored the following versions that require a different python version: 0.1.8 Requires-Python >=3.7,<3.11; 0.1.9 Requires-Python >=3.7,<3.11; 1.0.1 Requires-Python >=3.7,<3.11; 1.0.2 Requires-Python >=3.7,<3.11; 1.0.3 Requires-Python >=3.7,<3.11; 1.1.0 Requires-Python >=3.7,<3.11; 1.1.1 Requires-Python >=3.7,<3.12; 1.2.0 Requires-Python >=3.7,<3.12; 1.2.1 Requires-Python >=3.7,<3.12; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 2.0.0 Requires-Python >=3.7,<3.12; 2.1.0 Requires-Python >=3.7,<3.12
ERROR: Could not find a version that satisfies the requirement pyqtdarktheme>=2.1.0 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7)
ERROR: No matching distribution found for pyqtdarktheme>=2.1.0

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
(venv) PS D:\Blender Stuff\\ntscqt\pluscompilebetter\ntscQTplus>

**Comment by c4artisan** [comment]
use python 3.9

**Comment by c4artisan** [comment]
if you install it from the microsoft store, then from now on use python3.9 and pip3.9 in the command line

**Comment by Novahem** [comment]
This did work! As stated in the issue I installed python with Scoop, but I was able to just run `scoop install python39` and then it worked! I didn't even need to use python3.9 in the command line. Unfortunately I am now running into lots of issues using pyinstaller but I'll work through those myself. Thanks!
